server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simple-microservice
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework: INFO

management:
  endpoints:
    web:
      # endpoints mana saja yang di‐expose lewat HTTP
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    # selalu tunjukkan detail health (up/down) di response
    health:
      show-details: always
